Save a copy in Drive of the given notebook and make changes.

Output for each of the questions is provided below each question. You need to produce the same output.

In [ ]:
import numpy as np

 1. Create a 4x6 matrix filled with all zeros.

In [ ]:
import numpy as np
matrix = np.zeros((4, 6))
print(matrix)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


2. Create a 5x5 matrix filled with all ones.

In [ ]:
import numpy as np
matrix=np.ones((5,5))
print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.Create a matrix of (4,5) filled with 4.

In [ ]:
import numpy as np
matrix=np.full((4,5),4)
print(matrix)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


For questions 4-13, consider the matrix

a=[[1,2,3],[1,4,5],[8,4,2]]


4. Write a code to get print the shape of the given matrix.




In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
ShapeOfa = a.shape
print("Shape of a=", ShapeOfa)

Shape of the matrix a= (3, 3)


5.Write the code to print number of elements in a.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
NumberOfElements = a.size
print("Number of elements in a=", NumberOfElements)

Number of elements in a= 9


6. Print the 2nd row,1st column and element at (1,2) of a.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
SecondRowFirstColumn= a[1, 0]
element_at_1_2 = a[1, 2]
print("2nd row, 1st column:", SecondRowFirstColumn)
print("Element at (1,2):", element_at_1_2)

2nd row, 1st column: 1
Element at (1,2): 5


7. Change the element at (2,1) to 5.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
secondrow = a[1, :]
print("2nd row of matrix a=", secondrow)
firstcolumn = a[:, 0]
print("1st column of matrix a=", firstcolumn)
element_12 = a[1, 2]
print("Element at (1, 2) of matrix a=", element_12)

2nd row of matrix a= [1 4 5]
1st column of matrix a= [1 1 8]
Element at (1, 2) of matrix a= 5


8. Print the first and the last element of the first row using stepsize approach.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
first_and_last_first_row = a[0, 0::len(a[0])-1]
print("First and last element of the first row of matrix a=", first_and_last_first_row)

First and last element of the first row of matrix a= [1 3]


9. Print the maximum and minimum values of a.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
Maxvalue = np.max(a)
Minvalue = np.min(a)
print("Maximum value of matrix a=", Maxvalue)
print("Minimum value of matrix a=", Minvalue)

Maximum value of matrix a= 8
Minimum value of matrix a= 1


10. Print row-wise maximum values and their indicies of a.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
RowMaxvalues = np.max(a, axis=1)
RowMaxindices = np.argmax(a, axis=1)
for i in range(len(RowMaxvalues)):
    print(f"Row {i + 1}: Maximum value = {RowMaxvalues[i]} at index {RowMaxindices[i]}")

Row 1: Maximum value = 3 at index 2
Row 2: Maximum value = 5 at index 2
Row 3: Maximum value = 8 at index 0


11. Divide all the elements of a by 4.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
ResultantMatrix = a / 4
print("Resultant matrix=")
print(ResultantMatrix)

Resultant matrix=
[[0.25 0.5  0.75]
 [0.25 1.   1.25]
 [2.   1.   0.5 ]]


12. Sort a along the second axis.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
sorted_a = np.sort(a, axis=1)
print("Sorted matrix 'a' along the second axis:")
print(sorted_a)

Sorted matrix 'a' along the second axis:
[[1 2 3]
 [1 4 5]
 [2 4 8]]


13. Print the indices that would sort a along the second axis.

In [ ]:
a = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
indices= np.argsort(a, axis=1)
print("Indices that would sort matrix 'a' along the second axis=")
print(indices)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

14. Create an identity matrix of size 6x6.

In [ ]:

matrix=np.identity(6)
print(matrix)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


15. Let b=[1,4,3,2,6,8,5,4,2,0], split b into 3 arrays each of 3,4,3 elements.

In [ ]:
b = np.array([1, 4, 3, 2, 6, 8, 5, 4, 2, 0])
split_arrays = np.split(b, [3, 7])
for i, split_array in enumerate(split_arrays):
    print(f"Array {i + 1}: {split_array}")

Array 1: [1 4 3]
Array 2: [2 6 8 5]
Array 3: [4 2 0]


16.Create a 1-D array of 40 evenly spaced elements between 0. and 1., inclusive.

In [ ]:
array_40 = np.linspace(0, 1, 40,0.9)
print(array_40)

[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]


17. Mutliply given arrays element-wise.

a=[[4,7,2],[1,3,9]]

b=[[1,5,0],[2,7,5]]

In [ ]:
a = np.array([[4, 7, 2], [1, 3, 9]])
b = np.array([[1, 5, 0], [2, 7, 5]])
result = np.multiply(a, b)
print("Result=")
print(result)


Result=
[[ 4 35  0]
 [ 2 21 45]]


18. Create a 3x2 array with random values from 0 to 1.

In [ ]:
import numpy as np
random_array = np.random.rand(3, 2)
print(random_array)

[[0.23317515 0.81211653]
 [0.30680291 0.31188287]
 [0.44898784 0.95542739]]
